require:
  - rubocop-rails

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

Style/Documentation:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'db/migrate/20220514053050_devise_create_users.rb'
    - 'app/controllers/foods_controller.rb'
    - 'db/migrate/20220523142742_create_foods.rb'
    - 'app/uploaders/image_uploader.rb'
    - 'db/migrate/20220603113958_add_image_to_foods.rb'

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Rails/I18nLocaleTexts:
  Exclude:
    - 'app/controllers/foods_controller.rb'

AllCops:
  NewCops: enable
