require:
  - rubocop-rails

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

Style/Documentation:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'db/migrate/20220514053050_devise_create_users.rb'

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

AllCops:
  NewCops: enable
